name: Code Format
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  format_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive .
      - name: Force fail when the code is not formatted
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1
  format_js_and_html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: "! (./node_modules/.bin/js-beautify -s 2 -n -rf templates/* src/index.js | grep -v unchanged)"
